# Site settings
title: "Dot By Dot"
email: jacoblindey@gmail.com
description: "Jacob Lindey's Blog"
baseurl: ""
url: 
title_description: "This is the personal site for me, Jacob Lindey. I'm a software engineer making enterprise and embedded systems in the electronics manufacturing industry. I'm constantly searching for opportunities to explore new ideas in the design, development, and management of good software and I'll share what I find here."
title_image: "https://i.imgur.com/i0Tl4Ku.png"
google_analytics: 
disqus_account: 
github_repository: https://github.com/jacoblindey/jacoblindey.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  jacoblindey
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Built using <a href=\"https://jekyllrb.com/\">Jekyll</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/JacobLindey/JacobLindey.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
